### ISSUE TITLE
It's not clear what the URL field is for

### ISSUE THREAD

**Issue by zachlatta** [hackedu/shipit#2]
Maybe give it a better, more descriptive name. Run this by @TheThirdOne before closing.

**Comment by zachlatta** [comment]
What about "Link to live project"?

--
Zach Latta http://zachlatta.com https://github.com/zachlatta
https://twitter.com/zachlatta


On Tue, Jan 6, 2015, at 03:28 PM, Max Wofford wrote:
> How does 'live project' sound? @TheThirdOne[1]


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/TheThirdOne
  2. https://github.com/hackedu/shipit/issues/2#issuecomment-68953916

**Comment by TheThirdOne** [comment]
Live project doesn't sound right. It doesn't work well for any project that has a page for downloads for example.

**Comment by zachlatta** [comment]
What are your thoughts on just "Website"?

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by TheThirdOne** [comment]
"Website" may work, but for some projects that may still not make sense. For example, a project may essential use github as its main website. So i think "website (if applicable)" would be better.

**Comment by zachlatta** [comment]
Cool, I like "Website (if applicable)". The field is also optional in
the form. @MaxWofford, what are your thoughts?

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
"Website (if applicable) sounds good."

**Comment by zachlatta** [comment]
Do you want to take lead on implementing this?

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
I'll send a pull request in a few minutes.

**Comment by MaxWofford** [comment]
Should the 'optional' note be replaced by '(if applicable)'?

**Comment by zachlatta** [comment]
Nah, let's just go with "Website (if applicable) Optional".

**Comment by MaxWofford** [comment]
Submitted PR #25.

**Comment by zachlatta** [comment]
Merged.
