### ISSUE TITLE
Authentication is not required

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/shipit#24]
Users should be redirected to sign-in through github when they go to '/projects/new' without authenticating. 

EDIT: This is closed by #26

**Comment by MaxWofford** [comment]
How can we tell when the user authenticates through github?

**Comment by zachlatta** [comment]
Not sure if it's the best way, but you can check if
`req.session.passport.user` is available.

--
Zach Latta http://zachlatta.com https://github.com/zachlatta
https://twitter.com/zachlatta


On Fri, Jan 9, 2015, at 11:42 AM, Max Wofford wrote:
> How can we tell when the user authenticates through github?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/hackedu/shipit/issues/24#issuecomment-69387440

**Comment by MaxWofford** [comment]
This wasn't closed when #26 was merged, but should have been.
