### ISSUE TITLE
Tab switching removes red background

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/shipit#28]
After switching back to the main page from another tab, the red background disappears. Tested with chrome on windows 8.
![bug](https://cloud.githubusercontent.com/assets/5891442/5909038/b37153ae-a561-11e4-9331-21bc60b0cd62.png)

**Comment by zachlatta** [comment]
I am unable to reproduce. Did we just find a bug in Chrome?
![recorded](https://cloud.githubusercontent.com/assets/992248/5909088/1e4253d6-a562-11e4-83a3-14bcc246749a.gif)

**Comment by MaxWofford** [comment]
Issue has only existed on chrome on windows. I have no clue what this is. Closing this until new info comes up about this.
