### ISSUE TITLE
Add github/twitter handles

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/shipit#30]
Currently there is no way to get in contact with project creators. Should this be a feature?

**Comment by zachlatta** [comment]
Yeah, we should definitely have a way to get in contact with the project
creators and source code. I don't know how useful a link to our GitHub
or Twitter would be useful, but I think a fork on GitHub badge would be
really useful.

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Fixed in 78e621645ef9068b39560d4ba10798d2d745a03e
