### ISSUE TITLE
Names should be in alphabetical order

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/shipit#31]
Styalistic change.

**Comment by zachlatta** [comment]
Yeah, good call. Can you take lead on this?Jekyll might have some
built-in sorting functions.

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Oops, this should be in [hackedu/shipped](https://github.com/hackedu/shipped)

**Comment by zachlatta** [comment]
Actually, it might be nice if ship it automatically also sorted the names by alphabetical order in the YAML file.
